### ISSUE TITLE
Cordova-lib 6.3.0 breaks gulp-cordova-build-android

### ISSUE THREAD

**Issue by ryd0rz** [SamVerschueren/gulp-cordova-build-android#26] opened 2016-07-29 15:19 UTC
Please update your dependencies to use cordova-lib@6.2.0.

Your module is currently broken without this.

**Comment by SamVerschueren** [comment] 2016-07-29 18:21
Can you provide me with more information? I am not able to reproduce to be honest as it still works.

Error message? Stack trace? Anything that can be helpfull.

**Comment by ryd0rz** [comment] 2016-07-30 03:52
I don't have any errors as many of the gulp-cordova build utilities don't
give error logging. I just recently noticed when I did an NPM install that
my gulp cordova builds were failing, and I had to do a diff merge of the
old npm modules vs the newly installed ones to find what packages changed
regarding the gulp-cordova modules, and reverted them back 1 by 1 until I
reverted cordova-lib back to 6.2.0, and noticed you guys are allowing
^6.0.0, which could be huge differences from the versions... I set it to
use @6.2.0 and it worked (side note: ^6.2.0 did not work... even that
version is too new).

No, i'm not sure what broke it, or why... just noticed my gulp builds
weren't working any longer and we are using almost all of the gulp-cordova
packages you guys maintain (author, description, xml, plugin, and the
latter).

I can send you the script with all project specific information stripped
out if you'd like.

Thanks,
(ryd0rz)

**Comment by ryd0rz** [comment] 2016-07-30 03:53
Please note: This was only seen on gulp-cordova-build-ios, and I created this ticket here just because i'm not sure if android is also broken... but i'd think it would also be broken if the iOS one is broken, since they both use the cordova-lib dependency.

**Comment by SamVerschueren** [comment] 2016-08-02 09:39
It looks like `cordova-lib@6.3.0` indeed did some breaking changes https://github.com/SamVerschueren/gulp-cordova-create/issues/12. I'll remove the semver range caret symbol and make sure `6.2.0` is being used.

**Comment by SamVerschueren** [comment] 2016-12-06 11:23
I use this library quite heavily and it works quite well. So going to close this issue as I don't think this library is affected.

**Closed as completed by SamVerschueren** 2016-12-06 11:23 UTC
